print("Por favor digite los datos solicitados a continuación")
Identificacion=int(input("Número de identificación: "))
Nombres=str(input("Nombres: "))
Apellidos=str(input("Apellidos: "))
Direccion=str(input("Dirección: "))
Telefono=str(input("Teléfono: "))
Edad=int(input("Edad: "))
EstadoCivil=str(input("EstadoCivil: "))
NumeroDeHijos=int(input("Número de hijos: "))
Estatura=float(input("Estatura en centimetros: "))
FechaDeContratacion=str(input("Fecha de contratación (Día/mes/año): " ))
Sueldo=int(input("Sueldo Básico: "))
DiasLaborados=int(input("Días laborados: "))

print("-------------------------------------------------------------------")
print("El usuario es "+Nombres+" "+ Apellidos)
print("Su dirección es: "+ Direccion)
print("Su teléfono es: "+ Telefono)
print("Su edad es: "+ str(Edad))
print("su estado civil es:"+ EstadoCivil)
print("Reporta tener: "+ str(NumeroDeHijos)+" hijos")
print("Su estatura es:"+str(Estatura))
print("La fecha de su contratación es:"+FechaDeContratacion)
print("Su sueldo es: "+ str(Sueldo))
print("Usted ha laborado un total de :"+str(DiasLaborados))

